# Generated by Django 4.1.3 on 2022-11-27 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoList', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
